# Generated by Django 5.1.6 on 2025-02-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dicom_files/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.CharField(blank=True, max_length=64)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('study_date', models.DateTimeField(blank=True, null=True)),
                ('modality', models.CharField(blank=True, max_length=10)),
                ('study_description', models.TextField(blank=True)),
                ('series_description', models.TextField(blank=True)),
            ],
        ),
    ]
